package io.securecodebox.zap.service.engine.model.zap;

public enum ZapFields {

    ZAP_BASE_URL,
    ZAP_AUTHENTICATION,
    ZAP_SPIDER_MAX_DEPTH,
    ZAP_SPIDER_INCLUDE_REGEX,
    ZAP_SPIDER_EXCLUDE_REGEX,
    ZAP_SPIDER_EXCLUDE_DUPLICATES,
    ZAP_LOGIN_SITE,
    ZAP_LOGIN_USER,
    ZAP_USERNAME_FIELD_ID,
    ZAP_LOGIN_PW,
    ZAP_SCANNER_INCLUDE_REGEX,
    ZAP_SCANNER_EXCLUDE_REGEX,
    ZAP_PW_FIELD_ID,
    ZAP_LOGGED_IN_INDICATOR,
    LOGGED_OUT_INDICATOR,
    ZAP_SPIDER_API_SPEC_URL,
    ZAP_CSRF_TOKEN_ID,
}
